export const COLORS = [
  "Beige",
  "Black",
  "Blue",
  "Brown",
  "Green",
  "Grey",
  "Maroon",
  "Orange",
  "Pink",
  "Purple",
  "Red",
  "White",
  "Yellow",
];

export const SPEC_OPTIONS = {
  Fabric: [
    "Cotton",
    "Polyester",
    "Linen",
    "Denim",
    "Wool",
    "Silk",
    "Blend",
    "Spandex",
    "Rayon",
  ],
  Pattern: [
    "Solid",
    "Striped",
    "Checked",
    "Printed",
    "Graphic",
    "Textured",
    "Polka Dot",
    "Color Block",
  ],
  Fit: [
    "Regular Fit",
    "Slim Fit",
    "Oversized",
    "Relaxed Fit",
    "Skinny Fit",
    "Tapered",
  ],
  Collar: [
    "Polo",
    "Round Neck",
    "V-Neck",
    "Button-Down",
    "Mandarin",
    "Hooded",
    "Spread Collar",
  ],
  Sleeve: ["Half Sleeve", "Full Sleeve", "Sleeveless", "3/4 Sleeve"],
  Style: ["Casual", "Formal", "Party", "Streetwear", "Activewear", "Lounge"],
};

export const categories = {
  Topwear: {
    "T-shirts": [
      "Plain T-shirts",
      "Printed T-shirts",
      "Regular Fit T-shirts",
      "Oversized T-shirts",
      "Polo T-shirts",
      "Plus Size T-shirts",
      "Full Sleeve T-shirts",
    ],
    Shirts: [
      "Plain Shirts",
      "Oxford Shirts",
      "Flannel Shirts",
      "Satin Shirts",
      "Festive Shirts",
      "Cotton Shirts",
      "Shackets",
    ],
    Polos: [],
    "Shop For Women": ["Topwear", "Bottomwear"],
  },
  Bottomwear: {
    "Cargo Joggers": [],
    "Cargo Pants": [],
    Trousers: [],
    "Japanese Pants": [],
    "Gurkha Pants": [],
    "Korean Pants": [],
    Pyjamas: [],
    Jeans: [],
    Shorts: [],
    Boxers: [],
  },
  Combos: { General: [] },
  "New Arrivals": { General: [] },
  Winterwear: { General: [] },
};

export const defaultFormState = {
  title: "",
  mainCategory: "",
  subCategory: "",
  specificType: "",
  price: { original: "", discounted: "", offPercent: "" },
  sizes: [{ size: "S", stock: "" }],
  rating: "",
  color: "",
  description: "",
  specifications: {
    Fabric: "",
    Pattern: "",
    Fit: "",
    Collar: "",
    Sleeve: "",
    Style: "",
  },
  images: {
    preview: null,
    gallery: [
      { view: "Front View", file: null },
      { view: "Back View", file: null },
      { view: "Side View", file: null },
      { view: "Close-up View", file: null },
    ],
  },
};
